language: python
python:
  - 3.6
install:
  - git config remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
  - git fetch
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  - pytest
  - git diff -z --name-only origin/master... -- *.py | xargs -0 --no-run-if-empty pylint
  - git diff -U origin/master... | flake8 --diff -
  - sonar-scanner
branches:
  only:
    - master
addons:
  sonarcloud:
    organization: jawoszek-github
    token:
      secure: $SONAR_TOKEN
