language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  script:
  - pytest
  - git diff origin/master... -z --name-only -- *.py | xargs -0 pylint
  - git diff origin/master... -U | flake8 --diff -
